Remove mutate image ref
shipwright-io/operator pull request #128
Opened 2023-05-11 09:42 UTC by jkhelil

# Changes
Remove mutate_image_container_image reference

Fixes #<insert issue number here>
https://github.com/shipwright-io/operator/issues/127
-->

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [ ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ ] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/master/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes
```release-note
NONE
```

2023-05-11 09:47 UTC, jkhelil commented
docker pull ghcr.io/shipwright-io/build/image-processing
Using default tag: latest
Error response from daemon: Head https://ghcr.io/v2/shipwright-io/build/image-processing/manifests/latest: unauthorized


lets wait the package going public before merging this

2023-05-12 09:43 UTC, SaschaSchwarze0 requested changes
I think we will need to keep this PR open until v0.12 release is happening. Because only then we have the image-processing image in a release.

Anyway, good that we have it already prepared.

2023-05-12 09:43 UTC, SaschaSchwarze0 commented on kodata/release.yaml
> +              value: ghcr.io/shipwright-io/build/image-processing:0.11@sha256:e05d37529ef6d3d63fe161d54467733786b5117d888322f8b5804f27fb333624
Such a tag does not exist.

2023-07-26 13:26 UTC, qu1queee commented
From the Shipwright refinement meeting, PR is on-hold until the new release v0.12.0 is ready.

2023-08-04 13:44 UTC, adambkaplan commented
/hold

Per @qu1queee's comment.

Since the v0.12 release will lead to some refactoring of the operator, should we cut a "release candidate" of the build before we add it here?

2023-08-29 15:55 UTC, adambkaplan commented
We also have nightly releases yamls - those could be used ahead of a release as well.

2023-09-28 07:04 UTC, closed without merging