Update tekton operator deps
shipwright-io/operator pull request #234
Opened 2024-12-11 20:16 UTC by adambkaplan

# Changes

Update Tekton and k8s dependencies to most recent community supported versions, with related updates to code toolchains:

1. Golang to v1.22
2. k8s to 1.30.z
3. Tekton Operator to v0.74.z

Prerequisite for #230 

Fixes #178 

# Submitter Checklist

- [x] Includes tests if functionality changed/was added
- [x] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
action required: Minimum validated Tekton Operator version is v0.74.0; minimum validated Kubernetes version is v1.30.6. Other tooling such as Kustomize and controller-gen also updated to k8s 1.30 compatible versions.
```

2024-12-12 15:17 UTC, SaschaSchwarze0 requested changes

2024-12-16 21:00 UTC, adambkaplan commented on go.mod
> +	k8s.io/api v0.30.1
they just cut 1.30.8 last week :smile_cat: - will update.

2024-12-16 21:06 UTC, adambkaplan commented on go.mod
> +toolchain go1.23.3
done!

2024-12-16 21:06 UTC, adambkaplan commented
@SaschaSchwarze0 updated per your feedback - ptal

2024-12-17 06:50 UTC, SaschaSchwarze0 approved these changes
/approve
/lgtm

2024-12-17 06:54 UTC, merged