Test operator using a file-based catalog
shipwright-io/operator pull request #62
Opened 2022-03-22 18:59 UTC by adambkaplan

# Changes

- Created a file-based catalog using existing manifests for Shipwright and
  Tekton releases on operatorhub.io.
- Add script to render a candidate OLM catalog using the file based
  structure that includes the built bundle image.
- Update OLM subscription to use the "candidate" channel from the new
  file-based catalog.
- Add output directory to .gitignore
- Add documentation for OLM testing
- Bump operator version to 0.8.1-snapshot
- Restore the "run operator with catalog" step in CI

Fixes #57 

/kind cleanup

# Submitter Checklist

- [x] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/master/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

2022-03-23 07:42 UTC, SaschaSchwarze0 requested changes

2022-03-23 07:42 UTC, SaschaSchwarze0 commented on hack/render-candidate-catalog.sh
> +set -o pipefail
```suggestion
set -euo pipefail
```

2022-03-23 07:42 UTC, SaschaSchwarze0 commented on hack/render-candidate-catalog.sh
> +#! /usr/bin/env bash
Copyright missing.

2022-03-23 07:42 UTC, SaschaSchwarze0 commented on hack/render-candidate-catalog.sh
> +${SED_BIN} -i -E 's|"name": "shipwright-operator-latest"|"name": "shipwright-operator.v'"${VERSION}"'"|g' "${channelSpec}"
I think you refer here to `CSV_VERSION` as specified in Makefile:290.

```suggestion
${SED_BIN} -i -E 's|"name": "shipwright-operator-latest"|"name": "shipwright-operator.v'"${CSV_VERSION}"'"|g' "${channelSpec}"
```

2022-03-24 12:46 UTC, adambkaplan commented on hack/render-candidate-catalog.sh
> +#! /usr/bin/env bash
fixed in latest push

2022-03-25 13:42 UTC, adambkaplan reviewed
@SaschaSchwarze0 Incorporated your changes, and added a few fixes to get the e2e's working with Github Actions

2022-03-25 13:46 UTC, SaschaSchwarze0 approved these changes
/lgtm

2022-03-28 13:41 UTC, adambkaplan reviewed
/approve

2022-03-28 13:44 UTC, merged